apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: ticketin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName omis volontairement → utilise la StorageClass par défaut du cluster.
