apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: ticketin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName omis volontairement → utilise la StorageClass par défaut du cluster.
